baseURL = "https://hello-indigo.glitch.me/"
title = "Indigo Theme Demo"
copyright = "Copyright Â©, Copyright Owner Name"
languageCode = "en-US"
theme = "indigo"

[params]
  Author = "Site Author Name"
  Description = "Description of website for head meta tag"
  Subtitle = "A subtitle for your site"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = true
  PermalinkText = "ðŸ”—"
  mainSections = ["post", "release"]

  # Contact/social-network identifiers for social icons
  EmailAddress = "email.address@example.com"
  FacebookUser = "FacebookUserName"
  FlickrUser = "FlickrUserName"
  GitHubUser = "GitHubUserName"
  GitLabUser = "GitLabUserName"
  GlitchUser = "GlitchUserName"
  KeybaseUser = "KeybaseUserName"
  LinkedInUser = "LinkedInUserName"
  MediumUser = "MediumUserName"
  MicroBlogUser = "MicroBlogUserName"
  RedditUser = "RedditUserName"
  StackOverflowUser = "StackOverflowUserName"
  TumblrUser = "TumblrUserName"
  TwitterUser = "TwitterUserName"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "email.address@example.com"
    FlickrUser = "FlickrUserName"
    GitHubUser = "GitHubUserName"
    TwitterUser = "TwitterUserName"
    MicroBlogUser = "MicroBlogUserName"
    Country = "CountryName"
    City = "CityName"
